# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import iris_pb2 as protos_dot_iris__pb2


class IrisStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/protos.Iris/Predict',
        request_serializer=protos_dot_iris__pb2.IrisRequest.SerializeToString,
        response_deserializer=protos_dot_iris__pb2.IrisResponse.FromString,
        )


class IrisServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IrisServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=protos_dot_iris__pb2.IrisRequest.FromString,
          response_serializer=protos_dot_iris__pb2.IrisResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.Iris', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
