# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/iris.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/iris.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11protos/iris.proto\x12\x06protos\x1a\x1cgoogle/api/annotations.proto\"\x1b\n\x0bIrisRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"\x1d\n\x0cIrisResponse\x12\r\n\x05label\x18\x01 \x03(\r2N\n\x04Iris\x12\x46\n\x07Predict\x12\x13.protos.IrisRequest\x1a\x14.protos.IrisResponse\"\x10\x82\xd3\xe4\x93\x02\n\"\x05/iris:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_IRISREQUEST = _descriptor.Descriptor(
  name='IrisRequest',
  full_name='protos.IrisRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='protos.IrisRequest.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=86,
)


_IRISRESPONSE = _descriptor.Descriptor(
  name='IrisResponse',
  full_name='protos.IrisResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='protos.IrisResponse.label', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['IrisRequest'] = _IRISREQUEST
DESCRIPTOR.message_types_by_name['IrisResponse'] = _IRISRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IrisRequest = _reflection.GeneratedProtocolMessageType('IrisRequest', (_message.Message,), dict(
  DESCRIPTOR = _IRISREQUEST,
  __module__ = 'protos.iris_pb2'
  # @@protoc_insertion_point(class_scope:protos.IrisRequest)
  ))
_sym_db.RegisterMessage(IrisRequest)

IrisResponse = _reflection.GeneratedProtocolMessageType('IrisResponse', (_message.Message,), dict(
  DESCRIPTOR = _IRISRESPONSE,
  __module__ = 'protos.iris_pb2'
  # @@protoc_insertion_point(class_scope:protos.IrisResponse)
  ))
_sym_db.RegisterMessage(IrisResponse)



_IRIS = _descriptor.ServiceDescriptor(
  name='Iris',
  full_name='protos.Iris',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=119,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='protos.Iris.Predict',
    index=0,
    containing_service=None,
    input_type=_IRISREQUEST,
    output_type=_IRISRESPONSE,
    serialized_options=_b('\202\323\344\223\002\n\"\005/iris:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_IRIS)

DESCRIPTOR.services_by_name['Iris'] = _IRIS

# @@protoc_insertion_point(module_scope)
