// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/iris_user_state.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector struct {
	Value                []float32 `protobuf:"fixed32,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{0}
}

func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (m *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(m, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetValue() []float32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetIrisRequest struct {
	IrisId               string   `protobuf:"bytes,1,opt,name=iris_id,json=irisId,proto3" json:"iris_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIrisRequest) Reset()         { *m = GetIrisRequest{} }
func (m *GetIrisRequest) String() string { return proto.CompactTextString(m) }
func (*GetIrisRequest) ProtoMessage()    {}
func (*GetIrisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{1}
}

func (m *GetIrisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIrisRequest.Unmarshal(m, b)
}
func (m *GetIrisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIrisRequest.Marshal(b, m, deterministic)
}
func (m *GetIrisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIrisRequest.Merge(m, src)
}
func (m *GetIrisRequest) XXX_Size() int {
	return xxx_messageInfo_GetIrisRequest.Size(m)
}
func (m *GetIrisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIrisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIrisRequest proto.InternalMessageInfo

func (m *GetIrisRequest) GetIrisId() string {
	if m != nil {
		return m.IrisId
	}
	return ""
}

type GetIrisResponse struct {
	State                *Vector  `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIrisResponse) Reset()         { *m = GetIrisResponse{} }
func (m *GetIrisResponse) String() string { return proto.CompactTextString(m) }
func (*GetIrisResponse) ProtoMessage()    {}
func (*GetIrisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{2}
}

func (m *GetIrisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIrisResponse.Unmarshal(m, b)
}
func (m *GetIrisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIrisResponse.Marshal(b, m, deterministic)
}
func (m *GetIrisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIrisResponse.Merge(m, src)
}
func (m *GetIrisResponse) XXX_Size() int {
	return xxx_messageInfo_GetIrisResponse.Size(m)
}
func (m *GetIrisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIrisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIrisResponse proto.InternalMessageInfo

func (m *GetIrisResponse) GetState() *Vector {
	if m != nil {
		return m.State
	}
	return nil
}

type UpdateIrisRequest struct {
	IrisId               string   `protobuf:"bytes,1,opt,name=iris_id,json=irisId,proto3" json:"iris_id,omitempty"`
	Params               *Vector  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateIrisRequest) Reset()         { *m = UpdateIrisRequest{} }
func (m *UpdateIrisRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateIrisRequest) ProtoMessage()    {}
func (*UpdateIrisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{3}
}

func (m *UpdateIrisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIrisRequest.Unmarshal(m, b)
}
func (m *UpdateIrisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIrisRequest.Marshal(b, m, deterministic)
}
func (m *UpdateIrisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIrisRequest.Merge(m, src)
}
func (m *UpdateIrisRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateIrisRequest.Size(m)
}
func (m *UpdateIrisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIrisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIrisRequest proto.InternalMessageInfo

func (m *UpdateIrisRequest) GetIrisId() string {
	if m != nil {
		return m.IrisId
	}
	return ""
}

func (m *UpdateIrisRequest) GetParams() *Vector {
	if m != nil {
		return m.Params
	}
	return nil
}

type UpdateIrisResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateIrisResponse) Reset()         { *m = UpdateIrisResponse{} }
func (m *UpdateIrisResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateIrisResponse) ProtoMessage()    {}
func (*UpdateIrisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{4}
}

func (m *UpdateIrisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIrisResponse.Unmarshal(m, b)
}
func (m *UpdateIrisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIrisResponse.Marshal(b, m, deterministic)
}
func (m *UpdateIrisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIrisResponse.Merge(m, src)
}
func (m *UpdateIrisResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateIrisResponse.Size(m)
}
func (m *UpdateIrisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIrisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIrisResponse proto.InternalMessageInfo

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserResponse struct {
	State                *Vector  `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{6}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetState() *Vector {
	if m != nil {
		return m.State
	}
	return nil
}

type UpdateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Params               *Vector  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{7}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateUserRequest) GetParams() *Vector {
	if m != nil {
		return m.Params
	}
	return nil
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{8}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type UpdateUserByIrisRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IrisId               string   `protobuf:"bytes,2,opt,name=iris_id,json=irisId,proto3" json:"iris_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserByIrisRequest) Reset()         { *m = UpdateUserByIrisRequest{} }
func (m *UpdateUserByIrisRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserByIrisRequest) ProtoMessage()    {}
func (*UpdateUserByIrisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{9}
}

func (m *UpdateUserByIrisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserByIrisRequest.Unmarshal(m, b)
}
func (m *UpdateUserByIrisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserByIrisRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserByIrisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserByIrisRequest.Merge(m, src)
}
func (m *UpdateUserByIrisRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserByIrisRequest.Size(m)
}
func (m *UpdateUserByIrisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserByIrisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserByIrisRequest proto.InternalMessageInfo

func (m *UpdateUserByIrisRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateUserByIrisRequest) GetIrisId() string {
	if m != nil {
		return m.IrisId
	}
	return ""
}

type UpdateUserByIrisResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserByIrisResponse) Reset()         { *m = UpdateUserByIrisResponse{} }
func (m *UpdateUserByIrisResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserByIrisResponse) ProtoMessage()    {}
func (*UpdateUserByIrisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb28854e0a95ed66, []int{10}
}

func (m *UpdateUserByIrisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserByIrisResponse.Unmarshal(m, b)
}
func (m *UpdateUserByIrisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserByIrisResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserByIrisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserByIrisResponse.Merge(m, src)
}
func (m *UpdateUserByIrisResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserByIrisResponse.Size(m)
}
func (m *UpdateUserByIrisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserByIrisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserByIrisResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Vector)(nil), "protos.Vector")
	proto.RegisterType((*GetIrisRequest)(nil), "protos.GetIrisRequest")
	proto.RegisterType((*GetIrisResponse)(nil), "protos.GetIrisResponse")
	proto.RegisterType((*UpdateIrisRequest)(nil), "protos.UpdateIrisRequest")
	proto.RegisterType((*UpdateIrisResponse)(nil), "protos.UpdateIrisResponse")
	proto.RegisterType((*GetUserRequest)(nil), "protos.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "protos.GetUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "protos.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "protos.UpdateUserResponse")
	proto.RegisterType((*UpdateUserByIrisRequest)(nil), "protos.UpdateUserByIrisRequest")
	proto.RegisterType((*UpdateUserByIrisResponse)(nil), "protos.UpdateUserByIrisResponse")
}

func init() { proto.RegisterFile("protos/iris_user_state.proto", fileDescriptor_cb28854e0a95ed66) }

var fileDescriptor_cb28854e0a95ed66 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcb, 0xea, 0xd3, 0x40,
	0x14, 0xc6, 0x49, 0x4a, 0x53, 0x3c, 0x62, 0x6b, 0x87, 0x60, 0xd2, 0xa1, 0xd8, 0x32, 0x88, 0xd4,
	0x2e, 0x1a, 0xa8, 0x0b, 0xa1, 0x4b, 0x37, 0x52, 0xdc, 0xa5, 0xd6, 0x6d, 0x19, 0xed, 0x50, 0x02,
	0x35, 0x13, 0x33, 0xd3, 0x82, 0x14, 0x37, 0xbe, 0x82, 0x8f, 0xe6, 0x2b, 0xf8, 0x06, 0xbe, 0x80,
	0xcc, 0xa5, 0xcd, 0x55, 0xa8, 0xff, 0xe5, 0x9c, 0x73, 0xf2, 0x7d, 0xbf, 0x73, 0x21, 0x30, 0xce,
	0x72, 0x2e, 0xb9, 0x88, 0x92, 0x3c, 0x11, 0xbb, 0x93, 0x60, 0xf9, 0x4e, 0x48, 0x2a, 0xd9, 0x42,
	0x87, 0x91, 0x67, 0xb2, 0x78, 0x7c, 0xe0, 0xfc, 0x70, 0x64, 0x11, 0xcd, 0x92, 0x88, 0xa6, 0x29,
	0x97, 0x54, 0x26, 0x3c, 0x15, 0xa6, 0x8a, 0x3c, 0x07, 0xef, 0x23, 0xfb, 0x2c, 0x79, 0x8e, 0x7c,
	0xe8, 0x9e, 0xe9, 0xf1, 0xc4, 0x42, 0x67, 0xda, 0x99, 0xb9, 0xb1, 0x79, 0x90, 0x57, 0xd0, 0x7f,
	0xc7, 0xe4, 0x3a, 0x4f, 0x44, 0xcc, 0xbe, 0x9e, 0x98, 0x90, 0x28, 0x80, 0x9e, 0x36, 0x4c, 0xf6,
	0xa1, 0x33, 0x75, 0x66, 0x8f, 0x62, 0x4f, 0x3d, 0xd7, 0x7b, 0xf2, 0x06, 0x06, 0xb7, 0x52, 0x91,
	0xf1, 0x54, 0x30, 0xf4, 0x02, 0xba, 0x1a, 0x49, 0x57, 0x3e, 0x5e, 0xf6, 0x8d, 0xa9, 0x58, 0x18,
	0xcb, 0xd8, 0x24, 0xc9, 0x07, 0x18, 0x6e, 0xb3, 0x3d, 0x95, 0xec, 0x1e, 0x1b, 0xf4, 0x12, 0xbc,
	0x8c, 0xe6, 0xf4, 0x8b, 0x08, 0xdd, 0x56, 0x51, 0x9b, 0x25, 0x3e, 0xa0, 0xb2, 0xaa, 0x21, 0xb2,
	0xfd, 0x6c, 0x05, 0xcb, 0x4b, 0x46, 0x7a, 0x76, 0x85, 0x91, 0x7a, 0xde, 0xfa, 0x31, 0xa5, 0x0f,
	0xeb, 0xe7, 0x1e, 0x9b, 0xff, 0xef, 0xa7, 0x4c, 0x44, 0xde, 0x43, 0x50, 0x44, 0xdf, 0x7e, 0xab,
	0x4d, 0xb0, 0xdd, 0xb1, 0x34, 0x5a, 0xb7, 0xb2, 0x41, 0x0c, 0x61, 0x53, 0xcc, 0x18, 0x2d, 0xff,
	0x74, 0xe0, 0x89, 0x0a, 0xa8, 0xd4, 0x46, 0xb5, 0x89, 0x36, 0xd0, 0xb3, 0xfb, 0x46, 0xcf, 0xae,
	0xcc, 0xd5, 0x5b, 0xc1, 0x41, 0x23, 0x6e, 0xb1, 0x83, 0x1f, 0xbf, 0x7e, 0xff, 0x74, 0x87, 0x68,
	0xa0, 0x8f, 0x37, 0xba, 0x58, 0x9e, 0xef, 0x68, 0x07, 0x50, 0x6c, 0x0d, 0x8d, 0xae, 0xdf, 0x37,
	0xee, 0x03, 0xe3, 0xb6, 0x94, 0x55, 0xc7, 0x5a, 0xdd, 0x27, 0x75, 0xf5, 0x95, 0x33, 0xb7, 0xd4,
	0xaa, 0x8b, 0x0a, 0x75, 0x69, 0x55, 0x15, 0xea, 0xca, 0xb0, 0x0b, 0x6a, 0x35, 0xc9, 0xe8, 0x62,
	0xc7, 0x5b, 0xa2, 0xd6, 0xba, 0x35, 0xea, 0xb2, 0x34, 0x6e, 0x4b, 0x35, 0xa8, 0xab, 0xea, 0x8a,
	0xfa, 0x0c, 0x4f, 0xeb, 0x9b, 0x41, 0x93, 0xa6, 0x56, 0xe5, 0x00, 0xf0, 0xf4, 0xdf, 0x05, 0xd6,
	0x72, 0xa2, 0x2d, 0x47, 0xc4, 0xaf, 0x59, 0xea, 0xb9, 0xad, 0x9c, 0xf9, 0x27, 0xf3, 0x13, 0x79,
	0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xb2, 0xc5, 0xe3, 0x6b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IrisUserStateClient is the client API for IrisUserState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IrisUserStateClient interface {
	GetIris(ctx context.Context, in *GetIrisRequest, opts ...grpc.CallOption) (*GetIrisResponse, error)
	UpdateIris(ctx context.Context, in *UpdateIrisRequest, opts ...grpc.CallOption) (*UpdateIrisResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	UpdateUserByIris(ctx context.Context, in *UpdateUserByIrisRequest, opts ...grpc.CallOption) (*UpdateUserByIrisResponse, error)
}

type irisUserStateClient struct {
	cc *grpc.ClientConn
}

func NewIrisUserStateClient(cc *grpc.ClientConn) IrisUserStateClient {
	return &irisUserStateClient{cc}
}

func (c *irisUserStateClient) GetIris(ctx context.Context, in *GetIrisRequest, opts ...grpc.CallOption) (*GetIrisResponse, error) {
	out := new(GetIrisResponse)
	err := c.cc.Invoke(ctx, "/protos.IrisUserState/GetIris", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisUserStateClient) UpdateIris(ctx context.Context, in *UpdateIrisRequest, opts ...grpc.CallOption) (*UpdateIrisResponse, error) {
	out := new(UpdateIrisResponse)
	err := c.cc.Invoke(ctx, "/protos.IrisUserState/UpdateIris", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisUserStateClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/protos.IrisUserState/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisUserStateClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/protos.IrisUserState/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *irisUserStateClient) UpdateUserByIris(ctx context.Context, in *UpdateUserByIrisRequest, opts ...grpc.CallOption) (*UpdateUserByIrisResponse, error) {
	out := new(UpdateUserByIrisResponse)
	err := c.cc.Invoke(ctx, "/protos.IrisUserState/UpdateUserByIris", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IrisUserStateServer is the server API for IrisUserState service.
type IrisUserStateServer interface {
	GetIris(context.Context, *GetIrisRequest) (*GetIrisResponse, error)
	UpdateIris(context.Context, *UpdateIrisRequest) (*UpdateIrisResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	UpdateUserByIris(context.Context, *UpdateUserByIrisRequest) (*UpdateUserByIrisResponse, error)
}

func RegisterIrisUserStateServer(s *grpc.Server, srv IrisUserStateServer) {
	s.RegisterService(&_IrisUserState_serviceDesc, srv)
}

func _IrisUserState_GetIris_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIrisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisUserStateServer).GetIris(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IrisUserState/GetIris",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisUserStateServer).GetIris(ctx, req.(*GetIrisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IrisUserState_UpdateIris_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIrisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisUserStateServer).UpdateIris(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IrisUserState/UpdateIris",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisUserStateServer).UpdateIris(ctx, req.(*UpdateIrisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IrisUserState_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisUserStateServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IrisUserState/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisUserStateServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IrisUserState_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisUserStateServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IrisUserState/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisUserStateServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IrisUserState_UpdateUserByIris_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserByIrisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IrisUserStateServer).UpdateUserByIris(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IrisUserState/UpdateUserByIris",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IrisUserStateServer).UpdateUserByIris(ctx, req.(*UpdateUserByIrisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IrisUserState_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.IrisUserState",
	HandlerType: (*IrisUserStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIris",
			Handler:    _IrisUserState_GetIris_Handler,
		},
		{
			MethodName: "UpdateIris",
			Handler:    _IrisUserState_UpdateIris_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _IrisUserState_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _IrisUserState_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateUserByIris",
			Handler:    _IrisUserState_UpdateUserByIris_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/iris_user_state.proto",
}
