# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import iris_user_state_pb2 as protos_dot_iris__user__state__pb2


class IrisUserStateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetIris = channel.unary_unary(
        '/protos.IrisUserState/GetIris',
        request_serializer=protos_dot_iris__user__state__pb2.GetIrisRequest.SerializeToString,
        response_deserializer=protos_dot_iris__user__state__pb2.GetIrisResponse.FromString,
        )
    self.UpdateIris = channel.unary_unary(
        '/protos.IrisUserState/UpdateIris',
        request_serializer=protos_dot_iris__user__state__pb2.UpdateIrisRequest.SerializeToString,
        response_deserializer=protos_dot_iris__user__state__pb2.UpdateIrisResponse.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/protos.IrisUserState/GetUser',
        request_serializer=protos_dot_iris__user__state__pb2.GetUserRequest.SerializeToString,
        response_deserializer=protos_dot_iris__user__state__pb2.GetUserResponse.FromString,
        )
    self.UpdateUser = channel.unary_unary(
        '/protos.IrisUserState/UpdateUser',
        request_serializer=protos_dot_iris__user__state__pb2.UpdateUserRequest.SerializeToString,
        response_deserializer=protos_dot_iris__user__state__pb2.UpdateUserResponse.FromString,
        )
    self.UpdateUserByIris = channel.unary_unary(
        '/protos.IrisUserState/UpdateUserByIris',
        request_serializer=protos_dot_iris__user__state__pb2.UpdateUserByIrisRequest.SerializeToString,
        response_deserializer=protos_dot_iris__user__state__pb2.UpdateUserByIrisResponse.FromString,
        )


class IrisUserStateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetIris(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateIris(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserByIris(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IrisUserStateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetIris': grpc.unary_unary_rpc_method_handler(
          servicer.GetIris,
          request_deserializer=protos_dot_iris__user__state__pb2.GetIrisRequest.FromString,
          response_serializer=protos_dot_iris__user__state__pb2.GetIrisResponse.SerializeToString,
      ),
      'UpdateIris': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateIris,
          request_deserializer=protos_dot_iris__user__state__pb2.UpdateIrisRequest.FromString,
          response_serializer=protos_dot_iris__user__state__pb2.UpdateIrisResponse.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=protos_dot_iris__user__state__pb2.GetUserRequest.FromString,
          response_serializer=protos_dot_iris__user__state__pb2.GetUserResponse.SerializeToString,
      ),
      'UpdateUser': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUser,
          request_deserializer=protos_dot_iris__user__state__pb2.UpdateUserRequest.FromString,
          response_serializer=protos_dot_iris__user__state__pb2.UpdateUserResponse.SerializeToString,
      ),
      'UpdateUserByIris': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserByIris,
          request_deserializer=protos_dot_iris__user__state__pb2.UpdateUserByIrisRequest.FromString,
          response_serializer=protos_dot_iris__user__state__pb2.UpdateUserByIrisResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.IrisUserState', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
